apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculator.fullname" . }}
  labels:
    {{- include "calculator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "calculator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
